config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: "tasks#index"
  get 'tasks/new', to: "tasks#new"
  get 'tasks/:id', to: "tasks#show", as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

   def index
   @tasks = Task.all
  end

    def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

   def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
   params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
 <h2>Edit the Task</h2>

 <%= form_for @task do |t| %>
  <div>
    <%= t.label :title %>
    <%= t.text_field :title %>
  </div>

  <div>
    <%= t.label :details %>
    <%= t.text_field :details %>
  </div>

  <%= t.submit "Update Task" %>
 <% end %>

app/views/tasks/index.html.erb
<h1>All my Tasks</h1>

<ul>
<% @tasks.each do |task| %>
  <li>  <%= link_to task.title, task_path(task) %>
  <p><%= task.details%></p></li>
   <%= link_to "Delete", task_path(task), method: :delete %> </li>
<% end %>

<%= link_to "+ Add a new task", tasks_new_path%>
</ul>

app/views/tasks/new.html.erb
<h1>Add a new Task</h1>

 <%= form_for @task do |t| %>
  <div>
    <%= t.label :title %>
    <%= t.text_field :title, placeholder: 'Do the laundry' %>
  </div>

  <div>
    <%= t.label :details %>
    <%= t.text_field :details %>
  </div>

  <%= t.submit "Submit" %>
 <% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>
  <%= @task.details %>
</p>

<p>
  <%= link_to "Back to List", tasks_path%>
</p>

<p>
  <%= link_to "Edit Task", edit_task_path%>
<p>